export const appConstants = {
    TODO_ADD : "TODO_ADD",
    TODO_DELETE : "TODO_DELETE",
    TODO_TOGGLE : "TODO_TOGGLE", 
    GET_TODOS_REQUEST : "GET_TODOS_REQUEST",
    GET_TODOS_SUCCESS : "GET_TODOS_SUCCESS",
    GET_TODOS_FAILURE : "GET_TODOS_FAILURE",
    ADD_COUNTER : "ADD_COUNTER",
    REDUCE_COUNTER : "REDUCE_COUNTER",
    
}